# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: https://www.danielbradley.net
gitlocation: https://github.com/danielrbradley/danielrbradley.github.io.git
gitbranch: gh-pages
title: DanielBradley.Net - The Argumentative Exception
description: >
    A place for me to air my oppinions about all things programming.

source: source/
blog: source/blog/
blogIndex: source/blog/index.cshtml
layouts: layouts
content: content
template: tools/empty-template.html
output: output/
deploy: deploy
themes: themes
